spring:
  liquibase:
    contexts: prod

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 1H
      cache-null-values: false
